### ISSUE TITLE
Colocate tests with functionality/units

### ISSUE THREAD

**Issue by poutler** [poutler/todolist-REST-api#1]
## Tests should reside close to the functionality they test

This aligns with fractal/feature folder structure, where all of the functionality for a feature is contained in one directory. It aids the reader (fellow devs and me-in-the-future) in reading comprehension, which makes maintaining the codebase much easier

## Ideal folder structure
```
src/
+-- featureOne/
       +-- controller.ts
       +-- handler.ts
       +-- handler.spec.ts
```

## Tasks
- [ ] Adjust Jest config for test matching
- [ ] Adjust tsconfig to exclude tests(?)
- [ ] Move existing tests
